# Copyright 2020 GitHub
# Copyright 2021-2025 Collabora, Ltd
#
# SPDX-License-Identifier: MIT

name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Do a deep checkout on main, for the git describe to work.
      - name: Deep checkout (for main branch)
        uses: "actions/checkout@v4"
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          fetch-depth: 0
      # Default shallow checkout OK everywhere else.
      - name: Shallow checkout
        uses: "actions/checkout@v4"
        if: "${{ github.ref != 'refs/heads/main' }}"

      - name: REUSE Compliance Check
        uses: "fsfe/reuse-action@v4"

      - name: Setup .NET
        uses: "actions/setup-dotnet@v4"
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      # On main, let's build at least single-platform binaries.
      - name: Build artifacts
        if: "${{ github.ref == 'refs/heads/main' }}"
        shell: pwsh
        env:
          BUILD_OS: "${{ runner.os }}"
          BUILD_REF: "${{ github.ref }}"
        run: ./Build-Artifacts.ps1

      - name: Upload artifacts to workflow
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: "actions/upload-artifact@v4"
        with:
          name: "PrettyRegistryXML-${{ runner.os }}"
          path: "out/${{ env.ARTIFACT_NAME }}.7z"
