# Copyright 2020 GitHub
# Copyright 2021 Collabora, Ltd
#
# SPDX-License-Identifier: MIT

name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1

      # On main, let's build at least single-platform binaries.
      - name: Build artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: pwsh
        env:
          BUILD_OS: ${{ runner.os }}
          BUILD_REF: ${{ github.ref }}
        run: ./Build-Artifacts.ps1
      - name: Upload artifacts to workflow
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v2
        with:
          name: PrettyRegistryXML-${{ runner.os }}
          path: out/${{ env.ARTIFACT_NAME }}.7z
