# Copyright 2020 GitHub
# Copyright 2021-2025 Collabora, Ltd
#
# SPDX-License-Identifier: MIT

name: Publish releases

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and upload release
    runs-on: "${{ matrix.config.os }}"
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: "actions/setup-dotnet@v4"
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build artifacts
        shell: pwsh
        env:
          BUILD_OS: "${{ runner.os }}"
          BUILD_REF: "${{ github.ref }}"
        run: ./Build-Artifacts.ps1

      - name: Upload artifacts to workflow
        uses: "actions/upload-artifact@v4"
        with:
          name: "PrettyRegistryXML-${{ runner.os }}"
          path: "out/${{ env.ARTIFACT_NAME }}.7z"

      - name: Upload artifacts to release
        uses: "svenstaro/upload-release-action@v2"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*.7z
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
