# Copyright 2021 Collabora, Ltd
#
# SPDX-License-Identifier: MIT

name: Update docs

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths-ignore:
      - docs/**
      - .github/**

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: |
          dotnet restore
          dotnet tool restore
      - name: Build and publish locally
        run: dotnet publish -c Release -o out --no-restore
      - name: Build docs
        shell: pwsh
        run: |
          $assemblies = Get-ChildItem out -Filter "PrettyRegistryXml.*.dll"
          foreach ($assembly in $assemblies) {
            $assemblyName = $assembly.BaseName
            dotnet tool run xmldocmd (Resolve-Path -Relative $assembly) docs --source ../src/$assemblyName --clean
          }
      - name: Commit and push if applicable
        run: |
          git add docs
          if ! git diff HEAD --quiet; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Automatic docs update"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
